### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by Cijin** [Cijin/shave#3]
This seems like a good option: https://github.com/markbates/goth/tree/master
This too, but not so sure about this one: https://github.com/casbin/casbin

**Comment by hsluoyz** [comment]
@Cijin you can use: https://github.com/casdoor/casdoor , which uses: https://github.com/markbates/goth/ as OAuth connector and https://github.com/casbin/casbin as authorization engine.

**Comment by Cijin** [comment]
Hey @hsluoyz, thank you for pointing that out. I will check it out.
